apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Network
metadata:
  name: orc-imported-provider-network
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: dev-test-cloud-config
  managementPolicy: unmanaged
  import:
    id: 316eeb47-1498-46b4-b39e-00ddf73bd2a5
