apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Subnet
metadata:
  name: orc-managed-ipv4
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: dev-test-cloud-config
  managementPolicy: managed
  networkRef: orc-managed-network
  resource:
    description: Example IPv4 subnet
    tags:
    - orc-test
    ipVersion: 4
    cidr: 192.168.0.0/24
    routerRef: orc-managed-router
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Subnet
metadata:
  name: orc-managed-ipv4-2
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: dev-test-cloud-config
  managementPolicy: managed
  networkRef: orc-managed-network
  resource:
    description: Example IPv4 subnet
    tags:
    - orc-test
    ipVersion: 4
    cidr: 192.168.1.0/24
    routerRef: orc-managed-router
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Subnet
metadata:
  name: orc-managed-ipv6
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: dev-test-cloud-config
  managementPolicy: managed
  networkRef: orc-managed-network
  resource:
    description: Example IPv6 subnet
    tags:
    - orc-test
    ipVersion: 6
    cidr: fd34:929d:1bc8:1cc5::/64
    routerRef: orc-managed-router
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Subnet
metadata:
  name: orc-managed-ipv6-2
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: dev-test-cloud-config
  managementPolicy: managed
  networkRef: orc-managed-network
  resource:
    description: Example IPv6 subnet
    tags:
    - orc-test
    ipVersion: 6
    cidr: fd77:e363:145b:7d2b::/64
    routerRef: orc-managed-router
