apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Subnet
metadata:
  name: orc-managed-ipv4
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: dev-test-cloud-config
  managementPolicy: managed
  networkRef: orc-managed-network
  resource:
    description: Example IPv4 subnet
    tags:
    - orc-test
    ipVersion: 4
    cidr: 192.168.0.0/24
    routerRef: orc-managed-router
