nameReference:
- kind: Secret
  fieldSpecs:
  - path: spec/cloudCredentialsRef/secretName
    kind: Network
  - path: spec/cloudCredentialsRef/secretName
    kind: Subnet
  - path: spec/cloudCredentialsRef/secretName
    kind: Port

- kind: Network
  fieldSpecs:
  - path: spec/networkRef
    kind: Subnet
  - path: spec/networkRef
    kind: Port
