---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - images
  - networks
  - ports
  - routerinterfaces
  - routers
  - securitygroups
  - subnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - images/status
  - networks/status
  - ports/status
  - routerinterfaces/status
  - routers/status
  - securitygroups/status
  - subnets/status
  verbs:
  - get
  - patch
  - update
