/*
Copyright 2024 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NetworkResourceSpecApplyConfiguration represents a declarative configuration of the NetworkResourceSpec type for use
// with apply.
type NetworkResourceSpecApplyConfiguration struct {
	Name                  *string  `json:"name,omitempty"`
	Description           *string  `json:"description,omitempty"`
	AdminStateUp          *bool    `json:"adminStateUp,omitempty"`
	DNSDomain             *string  `json:"dnsDomain,omitempty"`
	MTU                   *int32   `json:"mtu,omitempty"`
	PortSecurityEnabled   *bool    `json:"portSecurityEnabled,omitempty"`
	QOSPolicyID           *string  `json:"qosPolicyID,omitempty"`
	External              *bool    `json:"external,omitempty"`
	Shared                *bool    `json:"shared,omitempty"`
	VLANTransparent       *bool    `json:"vlanTransparent,omitempty"`
	AvailabilityZoneHints []string `json:"availabilityZoneHints,omitempty"`
}

// NetworkResourceSpecApplyConfiguration constructs a declarative configuration of the NetworkResourceSpec type for use with
// apply.
func NetworkResourceSpec() *NetworkResourceSpecApplyConfiguration {
	return &NetworkResourceSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithName(value string) *NetworkResourceSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithDescription(value string) *NetworkResourceSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithAdminStateUp sets the AdminStateUp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminStateUp field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithAdminStateUp(value bool) *NetworkResourceSpecApplyConfiguration {
	b.AdminStateUp = &value
	return b
}

// WithDNSDomain sets the DNSDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNSDomain field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithDNSDomain(value string) *NetworkResourceSpecApplyConfiguration {
	b.DNSDomain = &value
	return b
}

// WithMTU sets the MTU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MTU field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithMTU(value int32) *NetworkResourceSpecApplyConfiguration {
	b.MTU = &value
	return b
}

// WithPortSecurityEnabled sets the PortSecurityEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortSecurityEnabled field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithPortSecurityEnabled(value bool) *NetworkResourceSpecApplyConfiguration {
	b.PortSecurityEnabled = &value
	return b
}

// WithQOSPolicyID sets the QOSPolicyID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QOSPolicyID field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithQOSPolicyID(value string) *NetworkResourceSpecApplyConfiguration {
	b.QOSPolicyID = &value
	return b
}

// WithExternal sets the External field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the External field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithExternal(value bool) *NetworkResourceSpecApplyConfiguration {
	b.External = &value
	return b
}

// WithShared sets the Shared field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Shared field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithShared(value bool) *NetworkResourceSpecApplyConfiguration {
	b.Shared = &value
	return b
}

// WithVLANTransparent sets the VLANTransparent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VLANTransparent field is set to the value of the last call.
func (b *NetworkResourceSpecApplyConfiguration) WithVLANTransparent(value bool) *NetworkResourceSpecApplyConfiguration {
	b.VLANTransparent = &value
	return b
}

// WithAvailabilityZoneHints adds the given value to the AvailabilityZoneHints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AvailabilityZoneHints field.
func (b *NetworkResourceSpecApplyConfiguration) WithAvailabilityZoneHints(values ...string) *NetworkResourceSpecApplyConfiguration {
	for i := range values {
		b.AvailabilityZoneHints = append(b.AvailabilityZoneHints, values[i])
	}
	return b
}
