/*
Copyright 2024 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NetworkResourceStatusApplyConfiguration represents a declarative configuration of the NetworkResourceStatus type for use
// with apply.
type NetworkResourceStatusApplyConfiguration struct {
	AdminStateUp          *bool                              `json:"adminStateUp,omitempty"`
	AvailabilityZoneHints []string                           `json:"availabilityZoneHints,omitempty"`
	AvailabilityZones     []string                           `json:"availabilityZones,omitempty"`
	CreatedAt             *string                            `json:"createdAt,omitempty"`
	DNSDomain             *string                            `json:"dnsDomain,omitempty"`
	ID                    *string                            `json:"id,omitempty"`
	IPV4AddressScope      *string                            `json:"ipv4AddressScope,omitempty"`
	IPV6AddressScope      *string                            `json:"ipv6AddressScope,omitempty"`
	L2Adjacency           *bool                              `json:"l2Adjacency,omitempty"`
	MTU                   *int32                             `json:"mtu,omitempty"`
	Name                  *string                            `json:"name,omitempty"`
	PortSecurityEnabled   *bool                              `json:"portSecurityEnabled,omitempty"`
	ProjectID             *string                            `json:"projectID,omitempty"`
	Segment               *NetworkSegmentApplyConfiguration  `json:",inline"`
	QOSPolicyID           *string                            `json:"qosPolicyID,omitempty"`
	RevisionNumber        *int32                             `json:"revisionNumber,omitempty"`
	External              *bool                              `json:"external,omitempty"`
	Segments              []NetworkSegmentApplyConfiguration `json:"segments,omitempty"`
	Shared                *bool                              `json:"shared,omitempty"`
	Status                *string                            `json:"status,omitempty"`
	Subnets               []string                           `json:"subnets,omitempty"`
	TenantID              *string                            `json:"tenantID,omitempty"`
	UpdatedAt             *string                            `json:"updatedAt,omitempty"`
	VLANTransparent       *bool                              `json:"vlanTransparent,omitempty"`
	Description           *string                            `json:"description,omitempty"`
	IsDefault             *bool                              `json:"isDefault,omitempty"`
	Tags                  []string                           `json:"tags,omitempty"`
}

// NetworkResourceStatusApplyConfiguration constructs a declarative configuration of the NetworkResourceStatus type for use with
// apply.
func NetworkResourceStatus() *NetworkResourceStatusApplyConfiguration {
	return &NetworkResourceStatusApplyConfiguration{}
}

// WithAdminStateUp sets the AdminStateUp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminStateUp field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithAdminStateUp(value bool) *NetworkResourceStatusApplyConfiguration {
	b.AdminStateUp = &value
	return b
}

// WithAvailabilityZoneHints adds the given value to the AvailabilityZoneHints field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AvailabilityZoneHints field.
func (b *NetworkResourceStatusApplyConfiguration) WithAvailabilityZoneHints(values ...string) *NetworkResourceStatusApplyConfiguration {
	for i := range values {
		b.AvailabilityZoneHints = append(b.AvailabilityZoneHints, values[i])
	}
	return b
}

// WithAvailabilityZones adds the given value to the AvailabilityZones field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AvailabilityZones field.
func (b *NetworkResourceStatusApplyConfiguration) WithAvailabilityZones(values ...string) *NetworkResourceStatusApplyConfiguration {
	for i := range values {
		b.AvailabilityZones = append(b.AvailabilityZones, values[i])
	}
	return b
}

// WithCreatedAt sets the CreatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreatedAt field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithCreatedAt(value string) *NetworkResourceStatusApplyConfiguration {
	b.CreatedAt = &value
	return b
}

// WithDNSDomain sets the DNSDomain field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DNSDomain field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithDNSDomain(value string) *NetworkResourceStatusApplyConfiguration {
	b.DNSDomain = &value
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithID(value string) *NetworkResourceStatusApplyConfiguration {
	b.ID = &value
	return b
}

// WithIPV4AddressScope sets the IPV4AddressScope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPV4AddressScope field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithIPV4AddressScope(value string) *NetworkResourceStatusApplyConfiguration {
	b.IPV4AddressScope = &value
	return b
}

// WithIPV6AddressScope sets the IPV6AddressScope field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IPV6AddressScope field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithIPV6AddressScope(value string) *NetworkResourceStatusApplyConfiguration {
	b.IPV6AddressScope = &value
	return b
}

// WithL2Adjacency sets the L2Adjacency field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the L2Adjacency field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithL2Adjacency(value bool) *NetworkResourceStatusApplyConfiguration {
	b.L2Adjacency = &value
	return b
}

// WithMTU sets the MTU field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MTU field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithMTU(value int32) *NetworkResourceStatusApplyConfiguration {
	b.MTU = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithName(value string) *NetworkResourceStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithPortSecurityEnabled sets the PortSecurityEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortSecurityEnabled field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithPortSecurityEnabled(value bool) *NetworkResourceStatusApplyConfiguration {
	b.PortSecurityEnabled = &value
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithProjectID(value string) *NetworkResourceStatusApplyConfiguration {
	b.ProjectID = &value
	return b
}

// WithSegment sets the Segment field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Segment field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithSegment(value *NetworkSegmentApplyConfiguration) *NetworkResourceStatusApplyConfiguration {
	b.Segment = value
	return b
}

// WithQOSPolicyID sets the QOSPolicyID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the QOSPolicyID field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithQOSPolicyID(value string) *NetworkResourceStatusApplyConfiguration {
	b.QOSPolicyID = &value
	return b
}

// WithRevisionNumber sets the RevisionNumber field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RevisionNumber field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithRevisionNumber(value int32) *NetworkResourceStatusApplyConfiguration {
	b.RevisionNumber = &value
	return b
}

// WithExternal sets the External field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the External field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithExternal(value bool) *NetworkResourceStatusApplyConfiguration {
	b.External = &value
	return b
}

// WithSegments adds the given value to the Segments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Segments field.
func (b *NetworkResourceStatusApplyConfiguration) WithSegments(values ...*NetworkSegmentApplyConfiguration) *NetworkResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSegments")
		}
		b.Segments = append(b.Segments, *values[i])
	}
	return b
}

// WithShared sets the Shared field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Shared field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithShared(value bool) *NetworkResourceStatusApplyConfiguration {
	b.Shared = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithStatus(value string) *NetworkResourceStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithSubnets adds the given value to the Subnets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Subnets field.
func (b *NetworkResourceStatusApplyConfiguration) WithSubnets(values ...string) *NetworkResourceStatusApplyConfiguration {
	for i := range values {
		b.Subnets = append(b.Subnets, values[i])
	}
	return b
}

// WithTenantID sets the TenantID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TenantID field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithTenantID(value string) *NetworkResourceStatusApplyConfiguration {
	b.TenantID = &value
	return b
}

// WithUpdatedAt sets the UpdatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedAt field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithUpdatedAt(value string) *NetworkResourceStatusApplyConfiguration {
	b.UpdatedAt = &value
	return b
}

// WithVLANTransparent sets the VLANTransparent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VLANTransparent field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithVLANTransparent(value bool) *NetworkResourceStatusApplyConfiguration {
	b.VLANTransparent = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithDescription(value string) *NetworkResourceStatusApplyConfiguration {
	b.Description = &value
	return b
}

// WithIsDefault sets the IsDefault field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsDefault field is set to the value of the last call.
func (b *NetworkResourceStatusApplyConfiguration) WithIsDefault(value bool) *NetworkResourceStatusApplyConfiguration {
	b.IsDefault = &value
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *NetworkResourceStatusApplyConfiguration) WithTags(values ...string) *NetworkResourceStatusApplyConfiguration {
	for i := range values {
		b.Tags = append(b.Tags, values[i])
	}
	return b
}
