/*
Copyright 2024 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// NetworkSegmentApplyConfiguration represents a declarative configuration of the NetworkSegment type for use
// with apply.
type NetworkSegmentApplyConfiguration struct {
	ProviderNetworkType     *string `json:"providerNetworkType,omitempty"`
	ProviderPhysicalNetwork *string `json:"providerPhysicalNetwork,omitempty"`
	ProviderSegmentationID  *int32  `json:"providerSegmentationID,omitempty"`
}

// NetworkSegmentApplyConfiguration constructs a declarative configuration of the NetworkSegment type for use with
// apply.
func NetworkSegment() *NetworkSegmentApplyConfiguration {
	return &NetworkSegmentApplyConfiguration{}
}

// WithProviderNetworkType sets the ProviderNetworkType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderNetworkType field is set to the value of the last call.
func (b *NetworkSegmentApplyConfiguration) WithProviderNetworkType(value string) *NetworkSegmentApplyConfiguration {
	b.ProviderNetworkType = &value
	return b
}

// WithProviderPhysicalNetwork sets the ProviderPhysicalNetwork field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderPhysicalNetwork field is set to the value of the last call.
func (b *NetworkSegmentApplyConfiguration) WithProviderPhysicalNetwork(value string) *NetworkSegmentApplyConfiguration {
	b.ProviderPhysicalNetwork = &value
	return b
}

// WithProviderSegmentationID sets the ProviderSegmentationID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProviderSegmentationID field is set to the value of the last call.
func (b *NetworkSegmentApplyConfiguration) WithProviderSegmentationID(value int32) *NetworkSegmentApplyConfiguration {
	b.ProviderSegmentationID = &value
	return b
}
